### PR TITLE
port entire hardened patch set

### PR DESCRIPTION
**Pull request by ghost**
This needs more testing and cleanup. Do not merge anywhere

### CODE REVIEW

**Comment by thestinger** [comment]
I'd rather make the configuration option changes via the defconfig. They need to exist in linux-hardened itself for other people using it to help guide them to make a better configuration.

**Comment by ghost** [comment]
@thestinger I just ported the entire thing with no exceptions from your old patches. We have to clean this up slowly

Example the x86 commits are useless for us

**Comment by ghost** [comment]
Removed accidentally added deny_new_usb patch in the rebase

**Comment by ghost** [comment]
@thestinger going to focus on first getting this to work and then can work on cleanup

**Comment by ghost** [comment]
Trying to find a breakage in USB. Might need a while

**Comment by ghost** [comment]
This can now be considered for merging

**Comment by thestinger** [comment]
@anupritaisno1 Can you resubmit this with per-topic branches as discussed? Thanks.

**Pull request closed without merging**
